// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw6-B1lIkaQeSgsL5bNWVJ68YYDlVG1eU',
    appId: '1:651607867670:web:a96ab70659552f92d9d037',
    messagingSenderId: '651607867670',
    projectId: 'flash-chat-50930',
    authDomain: 'flash-chat-50930.firebaseapp.com',
    storageBucket: 'flash-chat-50930.appspot.com',
    measurementId: 'G-PMLLLZYZC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaW4Y1EiWDL9fSoWPMxM9PRGkEfhNSqIE',
    appId: '1:651607867670:android:28ee751ea9086fbed9d037',
    messagingSenderId: '651607867670',
    projectId: 'flash-chat-50930',
    storageBucket: 'flash-chat-50930.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1soR-q_MqV-_0zT-nIcVjSsV5ftAleos',
    appId: '1:651607867670:ios:b9ed0b785af02bf1d9d037',
    messagingSenderId: '651607867670',
    projectId: 'flash-chat-50930',
    storageBucket: 'flash-chat-50930.appspot.com',
    iosClientId: '651607867670-0n7u7ok0n6couuevh1qr93habim5b9fd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1soR-q_MqV-_0zT-nIcVjSsV5ftAleos',
    appId: '1:651607867670:ios:b9ed0b785af02bf1d9d037',
    messagingSenderId: '651607867670',
    projectId: 'flash-chat-50930',
    storageBucket: 'flash-chat-50930.appspot.com',
    iosClientId: '651607867670-0n7u7ok0n6couuevh1qr93habim5b9fd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
